### ISSUE TITLE
Chocolatey version 2.0.0

### ISSUE THREAD

**Issue by regg00** [crazy-max/ghaction-chocolatey#157]
Would be nice to be able to use the v2.0.0 of Chocolatey with this GH action.

Goal is to use GitHub packages to host Chocolatey packages since v2.0.0 of Chocolatey now supports NuGet v3 feeds.

Probably just need to change the version number here: https://github.com/crazy-max/ghaction-chocolatey/blob/84f876ce8c3cb6f320b1ca03f48a47c10d9e3a15/image/Dockerfile#L3C1-L4C1

**Comment by crazy-max** [comment]
> Probably just need to change the version number here: https://github.com/crazy-max/ghaction-chocolatey/blob/84f876ce8c3cb6f320b1ca03f48a47c10d9e3a15/image/Dockerfile#L3C1-L4C1

Probably, contributions welcomed
